steps:
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'tmpproject', '.']
      args: ['run', '-p', '3000:3000', 'tmpproject']

timeout: '220s'